/* Confirmation-only actions. AIChat decides whether an action or an insight is needed. */
window.AIActions = (() => {
  const esc = value => String(value || '').replace(/[&<>]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;' }[char]));
  const label = proposal => { const d = proposal.data || {}, money = v => `R$ ${Number(v).toFixed(2).replace('.', ',')}`; const labels = { register_miles:`${d.operation==='remove'?'Resgatar':'Acumular'} ${d.amount} milhas em ${d.source}`, record_strength_workout:`Registrar ${d.count||1} treino(s) de força · ${d.date}`, record_pilates_workout:`Registrar ${d.count||1} treino(s) de pilates · ${d.date}`, record_run:`Registrar corrida: ${d.kilometers} km · ${d.date}`, create_income:`Registrar receita: ${d.description} · ${money(d.amount)} · ${d.date}`, credit_vr:`Registrar crédito de VR: ${money(d.amount)} · ${d.date}`, create_recurring_income:`Criar receita recorrente: ${d.description} · ${money(d.amount)} · dia ${d.day}`, complete_habit:`Concluir hábito · ${d.date}`, complete_task:`Concluir tarefa · ${d.date}`, register_water:`Registrar água: ${d.glasses} copo(s) · ${d.date}`, register_mood_energy:`Registrar humor e energia ${d.energy}/5 · ${d.date}` }; if (proposal.action === 'create_expense') return `Registrar gasto: ${d.description} · ${money(d.amount)} · ${d.date}`; if (proposal.action === 'create_task') return `Criar tarefa: ${d.text} · ${d.date}`; if (proposal.action === 'create_habit') return `Criar hábito: ${d.name}`; return labels[proposal.action] || 'Confirmar registro'; };
  function show(proposal) { const list = document.getElementById('aiMessages'); if (!proposal || !list) return false; const item = document.createElement('div'); item.className = 'ai-message assistant ai-proposal'; item.innerHTML = `<strong>Fadinha</strong><span>${esc(label(proposal))}</span><div><button type="button" class="ai-confirm">Confirmar</button><button type="button" class="ai-cancel">Agora não</button></div>`; list.appendChild(item); list.scrollTop = list.scrollHeight; item.querySelector('.ai-cancel').onclick = () => item.remove(); item.querySelector('.ai-confirm').onclick = async () => { const button = item.querySelector('.ai-confirm'); button.disabled = true; button.textContent = 'Registrando…'; try { const { data, error } = await supabaseClient.functions.invoke('ai-assistant', { body:{ operation:'execute_action', proposal } }); if (error) throw error; item.querySelector('span').textContent = data?.result || 'Registro criado.'; item.querySelector('div').remove(); } catch (error) { console.error('Falha ao registrar:', error); button.disabled = false; button.textContent = 'Tentar novamente'; } }; return true; }
  async function prepare(message) { try { const { data, error } = await supabaseClient.functions.invoke('ai-actions', { body:{ message } }); if (error) throw error; return show(data?.proposal); } catch (error) { console.warn('Não foi possível preparar ação:', error); return false; } }
  document.addEventListener('DOMContentLoaded', () => { const style = document.createElement('style'); style.textContent = `.ai-proposal{border:1px solid #e6c8d7}.ai-proposal div{display:flex;gap:6px;margin-top:8px}.ai-proposal button{border:0;border-radius:8px;padding:6px 9px;background:#a94772;color:#fff;font:700 12px Segoe UI,sans-serif;cursor:pointer}.ai-proposal .ai-cancel{background:#fff;color:#78465d;border:1px solid #e6c8d7}`; document.head.appendChild(style); });
  return { prepare };
})();
