/* Chat client. Gemini is called only by the authenticated Supabase Edge Function. */
window.AIChat = (() => {
  let busy=false, mounted=false;
  const esc=s=>String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
  function add(role,text){ const list=document.getElementById('aiMessages'); if(!list)return; const item=document.createElement('div'); item.className=`ai-message ${role}`; item.innerHTML=`<strong>${role==='user'?'Você':'Assistente'}</strong><span>${esc(text).replace(/\n/g,'<br>')}</span>`; list.appendChild(item); list.scrollTop=list.scrollHeight; }
  async function send(){ const input=document.getElementById('aiInput'), button=document.getElementById('aiSend'), message=input.value.trim(); if(!message||busy)return; busy=true; button.disabled=true; input.disabled=true; add('user',message); input.value=''; add('assistant','Pensando com seus dados…'); const pending=document.querySelector('#aiMessages .ai-message.assistant:last-child'); try { const {data,error}=await supabaseClient.functions.invoke('ai-assistant',{body:{message}}); if(error)throw error; pending.querySelector('span').textContent=data?.answer||'Não encontrei uma resposta para isso agora.'; } catch(error) { console.error('Falha no assistente:',error); pending.querySelector('span').textContent='Não consegui consultar seus dados agora. Verifique sua conexão e tente novamente.'; } finally {busy=false;button.disabled=false;input.disabled=false;input.focus();} }
  function mount(){ if(mounted||!window.supabaseClient)return; mounted=true; const style=document.createElement('style');style.textContent='.ai-chat{position:fixed;right:16px;bottom:66px;z-index:9998}.ai-toggle,.ai-compose button{border:0;border-radius:999px;padding:11px 15px;background:#ff8fb8;color:#fff;font:700 14px Segoe UI,sans-serif;cursor:pointer;box-shadow:0 5px 16px #0002}.ai-panel{position:absolute;right:0;bottom:54px;width:min(390px,calc(100vw - 32px));background:#fff;border:1px solid #eadff0;border-radius:20px;box-shadow:0 15px 45px #0003;overflow:hidden}.ai-panel.hidden{display:none}.ai-panel header{display:flex;justify-content:space-between;padding:14px 16px;background:#fff0f6}.ai-panel header button{border:0;background:transparent;font-size:22px;cursor:pointer}.ai-messages{max-height:330px;overflow:auto;padding:12px;display:grid;gap:9px}.ai-message{max-width:90%;padding:10px 12px;border-radius:13px;background:#f7f2fa;color:#574f6b;font:14px Segoe UI,sans-serif;line-height:1.4}.ai-message strong,.ai-message span{display:block}.ai-message strong{font-size:11px;margin-bottom:3px}.ai-message.user{justify-self:end;background:#ffe0ed}.ai-compose{display:flex;gap:8px;padding:12px;border-top:1px solid #eadff0}.ai-compose textarea{flex:1;resize:none;border:1px solid #eadff0;border-radius:10px;padding:8px;font:14px Segoe UI,sans-serif}.ai-compose button{border-radius:10px;padding:8px 11px}.ai-compose button:disabled{opacity:.6}@media(max-width:600px){.ai-chat{right:12px;bottom:62px}.ai-panel{width:calc(100vw - 24px)}}';document.head.appendChild(style); const root=document.createElement('aside'); root.className='ai-chat'; root.innerHTML='<button id="aiToggle" class="ai-toggle" type="button" aria-expanded="false">✨ Pergunte à Fadinha</button><section id="aiPanel" class="ai-panel hidden" aria-label="Assistente financeiro"><header><strong>✨ Assistente</strong><button id="aiClose" type="button" aria-label="Fechar">×</button></header><div id="aiMessages" class="ai-messages"><div class="ai-message assistant"><strong>Assistente</strong><span>Oi! Posso analisar suas finanças, tarefas, hábitos e compromissos usando somente os seus dados salvos.</span></div></div><div class="ai-compose"><textarea id="aiInput" rows="2" placeholder="Ex.: Quanto gastei com alimentação este mês?"></textarea><button id="aiSend" type="button">Enviar</button></div></section>'; document.body.appendChild(root); const panel=document.getElementById('aiPanel'),toggle=document.getElementById('aiToggle'); const close=()=>{panel.classList.add('hidden');toggle.setAttribute('aria-expanded','false')}; toggle.onclick=()=>{panel.classList.toggle('hidden');toggle.setAttribute('aria-expanded',String(!panel.classList.contains('hidden')))}; document.getElementById('aiClose').onclick=close; document.getElementById('aiSend').onclick=send; document.getElementById('aiInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}}); }
  return {mount};
})();
